# Пример создания нового босса:
# После boss(для создания новых боссов его не нужно еще раз писать): спускаемся вниз (клавиша Enter),
# далее пишем индификатор нашего босса, он никакой роли для вас не играет. Называйте как хотите
# Обязательно сохоаняем табуляцию! Далее, когда мы создали индификатор, напиример - name, ставим после него ':'
# Далее открыаем скобку [ и начинаем писать текст. Текст воспринимается только внутри символов "". Т.е - поставили символ " начали писать текст внутри,
# а когда закончили то закрываем его ".
# Что и где надо писать: ["Название босса", "Кастомный нейм босса", "Время через сколько он заспавнится", "Локация спавна"]
# Пример рабочего конфига:
# boss:
#   зомби: ["Королевский зомби", "Кинг зомбик", "25", "/base"]
#   ваше название: ["Название боса", "Кастомное имя", "время в минутах", "локация"]

# !!!!!!!!!!!!!!!
# И САМОЕ ГЛАВНОЕ. ЛЮБЫЕ ЗНАЧЕНИЯ КОТОРЫЕ ВЫ ПИШИТЕ, БУДЬ ЭТО ТЕКСТ ИЛИ ВРЕМЯ - ОБЯЗАТЕЛЬНО НУЖНЫ КАВЫЧКИ. ОДИНАРНЫЕ ИЛИ ДВОЙНЫЕ
# !!!!!!!!!!!!!!!
boss:
  1: [ "Королевский зомби", "Кинг зомбяка", "25", "/base" ]
  2: [ "Сточный слизень", "Хтрафранцуз", "60", "/mine 6" ]
  3: [ "Матка", "Паучара", "90", "/mine 10" ]
  4: [ "Йети", "Снежный хрен", "180", "/mine 15" ]
  5: [ "Коровка из Коровёнки", "Маман", "180", "/mine 13" ]
  6: [ "Левиафан", "Хрен из сверхов", "150", "/village" ]
  7: [ "Небесный владыка", "Бог с неба", "300", "/mine 23" ]
  8: [ "Хранитель подводного мира", "Водяной", "300", "/mine 18" ]
  9: [ "Холуй", "Холоп", "45", "/mine 5" ]
  10: [ "Фенрир", "Фирамир", "90", "/mine 5" ]
  11: [ "Все Всадники апокалипсиса", "Жгучие перцы", "150", "/mine 9" ]
  12: [ "Житель края", "Житель края", "240", "/mine 21" ]

# Включает уведомления в трее. Работает только в случае, если система поддерживает его или он у вас не выключен.
# true - включено, false - выключено
notification: 'true'

# Переключает режим звуковых оповещений полностью.
soundnotification: 'true'
# За сколько отправить уведомление о спавне босса
# Указывается в минутах
reminder_time: '5'
